### ISSUE TITLE
Stage 1 progress

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-Number.range#1]
https://tc39.github.io/process-document/
# Entrance Criteria

- [x] Identified “champion” who will advance the addition
- [x] Prose outlining the problem or need and the general shape of a solution
- [x] Illustrative examples of usage
- [x] High-level API
- [x] Discussion of key algorithms, abstractions and semantics
- [x] Identification of potential “cross-cutting” concerns and implementation challenges/complexity

# Implementation Types Expected

- [x] Polyfills / demos

**Comment by Jack-Works** [comment]
@LJHarb
Hello, should I transfer this repo to tc39 or I must find a champion first?

**Comment by ljharb** [comment]
Transfers only happen at stage 1, which requires both a champion and committee consensus.

(It’s a gray area whether proposals that have no delegate involvement are considered stage 0)
