### ISSUE TITLE
Comparison of Range in slice notation proposal

### ISSUE THREAD

**Issue by hax** [tc39/proposal-Number.range#13]
There are some [discussion in slice notation proposal](https://github.com/tc39/proposal-slice-notation/issues/19) which also suggest `Range`, copy from [C# index and range](https://github.com/tc39/proposal-slice-notation/issues/30). 

Basically, `Range` in that proposal is a little bit like `SafeIntegerRange`, and optimized for array index use case.

**Comment by Jack-Works** [comment]
If there is `Symbol.slice`, I'd like to add it to the return value of range (#12 )

**Comment by Jack-Works** [comment]
Looks like the slice notation proposal isn't active for these years, I'll close this for now.
